# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none

variables:
- group: myVG
- name: status
  value: 'Green'

stages:
- stage: Build
  displayName: Build stage
  condition: eq('true', variables['foo'])
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: PowerShell@2
      condition: eq('true', variables['foo'])
      inputs:
       targetType: 'inline'
       script: |
        Write-Host "foo: $(foo) status: $(status)"

